---
title: "Homework 9"
author: "T.J. Seislove"
date: "3/31/2026"
output:
  html_document:
      code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
library(tidyverse)
library(mosaic)
library(janitor)
library(knitr)
```

# Data Import

```{r}
babynames <- babynames::babynames
```

# New Columns

### Percent

```{r}
baby_names <- babynames %>% mutate(percent = round(prop * 100, 2))

head(baby_names) %>% kable()
```

^[Problem 1 Complete]

### Sentence

```{r}
baby_names <- baby_names %>% 
  mutate(sentence = str_glue("{percent}% in {year}"))

head(baby_names) %>% kable()
```

^[Problem 2 Complete]

# Filtering and Sampling

### Filter by Name and Sex

```{r}
baby_names <- baby_names %>% filter(name == 'Ben' & sex == 'M')

head(baby_names) %>% kable()
```

^[Problem 3 Complete]

### Pseudorandom Sample of 5 Rows

```{r}
set.seed(10)

baby_sample <- baby_names %>% slice_sample(n = 5) %>% arrange(year)

baby_sample %>% kable()
```

^[Problem 4 Complete]

# Formatting String

### Flattening

```{r}
baby_strings <- baby_sample %>% 
  pull(sentence)

flat_baby <- str_flatten(baby_strings, ", ", last = ", and ")

str_view(flat_baby)
```

^[Problem 5 Complete]

### Filling Format Template

```{r, results='asis'}
format_baby <- str_glue("Out of all male names, the name Ben represented {flat_baby}.")

cat(format_baby)
```

^[Problem 6 Complete]